import { colors } from './colors';

export default {
  name: 'LIGHT',
  color: {
    primary: colors.primary['500'],
    activeMenuItem: colors.primary['100'],
    inactiveMenuItem: colors.primary['250'],
    bgTabMenu: colors.primary['350'],
    borderTabMenu: colors.primary['350'],
    secondary: colors.primary['100'],
    success: '#75BF72',
    warning: '#db8818',
    danger: '#f44336',
    divider: '#CFD2D8',
    activeText: colors.neutral['100'],
    inactiveTabs: '#D9D9D9',
    blueLight: '#EDF1F9',
    bgHeaderEmpty: colors.primary['200'],
    bgFilterInactive: '#FFF',
    bgFiltersActive: '#F1F5FB',
    filterFocused: '#347AF0',
    filterDisabled: '#485068',
    titleNotImport: colors.primary['700'],
    title: colors.primary['700'],
    onboardingTitle: colors.neutral['900'],
    onboardingSubtitle: colors.primary['700'],
    subtitle: '#485068',
    blue: colors.secondary['400'],
    shadowBackdrop: colors.primary['250'],
    Ação: '#21897E',
    FII: '#69D1C5',
    ETF: '#69A1E5',
    BDR: '#8980F5',
    Outros: '#7EBCE6',
    Cripto: '#F7DD70',
    bgMenuSubheaderActive: '#FFF',
    bgMenuSubheaderInative: '#F1F5FB',
    bgCardPlan: '#F1F5FB',
    bgButtonOutlined: colors.primary['100'],
    bgButtonPrimary: colors.secondary['400'],
    activeStep: colors.secondary['400'],
    inactiveStep: colors.secondary['700'],
    bgAddButton: colors.secondary['300'],
    borderAddButton: colors.primary['250'],
    headerPrimary: colors.primary['500'],
    bgModalPrimary: colors.primary['300'],
    closeIcon: colors.primary['900'],
  },
  gradient: {
    darkToLightGreen: ['#31AD2C', '#2D9B28'],
    darkToLightBlue: ['#347AF0', '#5C8FE5', '#F2F2F7'],
    lightToGray: ['#FFF', '#EDF1F9'],
    lightToDarkGreen: ['#359846', '#4CD964', '#F2F2F7'],
    lightToDarkRed: ['#F44336', '#F2F2F7'],
  },
};
